#!/bin/sh 
date
export PS4=' $SECONDS + '
set -x

####################################
# obtain unique process id (pid) and make temp directory
####################################
#export jobid=${jobid:-$job.o$$}
export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA
export cycle=t${cyc}z

####################################
# File To Log Msgs
####################################
#export jlogfile=${jlogfile:-${DATA}/jlogfile.${jobid}}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-ens_tracker}
export RUN=${RUN:-aigfs}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"
export pgmerr=errfile

####################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDECF=${SENDECF:-NO}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEens_tracker=${HOMEens_tracker:-${PACKAGEHOME}}
export EXECens_tracker=${EXECens_tracker:-$HOMEens_tracker/exec}
export FIXens_tracker=${FIXens_tracker:-$HOMEens_tracker/fix}
export USHens_tracker=${USHens_tracker:-$HOMEens_tracker/ush}

##############################
# Run setpdy and initialize PDY variables
##############################
#setpdy.sh
#. ./PDY
export PDY=20251030
##############################################
# Define COM directories
##############################################
#export COMINaigfs=${COMINaigfs:-$(compath.py $envir/com/aigfs/${aigfs_ver})/aigfs.${PDY}}
export COMINaigfs=/lfs/h1/ops/prod/com/aigfs/v1.0/aigfs.${PDY}/${cyc}/model/atmos/grib2
export COMINsyn=${COMINsyn:-$(compath.py $envir/com/gfs/${gfs_ver})/syndat}

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${ens_tracker_ver})/${RUN}.${PDY}/${cyc}/tctrack}
export COMOUThur=${COMOUThur:-$(compath.py -o ${NET}/${ens_tracker_ver})/global}
export COMOUTatcf=${COMOUTatcf:-$(compath.py -o ${NET}/${ens_tracker_ver})/atcf}
mkdir -m 775 -p $COMOUT $COMOUThur $COMOUTatcf

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

#############################################################
# Execute the script
export cmodel=aigfs
export loopnum=1
export ymdh=${PDY}${cyc}

export aigfsdir=${COMINaigfs}
export pert=""
pertdir=${DATA}/${cmodel}
mkdir -p $pertdir

#-----------input data checking -----------------
${USHens_tracker}/data_check_aigfs.sh 
# exit code 6 = missing data of opportunity
if [ $? -eq 6 ]; then exit; fi
#------------------------------------------------

${USHens_tracker}/extrkr_ai.sh ${loopnum} ${cmodel} ${ymdh} ${pertdir} ${pert} #2>&1 >${outfile}

export err=$?; err_chk

if [ "$SENDCOM" = 'YES' ]; then
  if [ -s ${pertdir}/trak.agfs.atcfunix.${PDY}${cyc} ]; then
    cp ${pertdir}/trak.agfs.atcfunix.${PDY}${cyc} ${COMOUT}/agfs.t${cyc}z.cyclone.trackatcfunix

    cat ${pertdir}/trak.agfs.atcfunix.${PDY}${cyc} | \
      sed s:agfs:AGFS:g \
    > ${COMOUT}/agfs.t${cyc}z.cyclone.trackatcfunix
  fi
fi

#############################################################

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
if [[ $KEEPDATA != "YES" ]]; then
  rm -rf $DATA
fi

date
