#!/bin/sh 
date
export PS4=' $SECONDS + '
set -x

####################################
# obtain unique process id (pid) and make temp directory
####################################
export jobid=${jobid:-$job.o$$}
export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA
export cycle=t${cyc}z

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${jobid}}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-ens_tracker}
export RUN=${RUN:-ecme}
export model_id=${model_id:-ecme}
####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"
export pgmerr=errfile

####################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDECF=${SENDECF:-NO}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEens_tracker=${HOMEens_tracker:-${PACKAGEHOME}}
export EXECens_tracker=${EXECens_tracker:-$HOMEens_tracker/exec}
export FIXens_tracker=${FIXens_tracker:-$HOMEens_tracker/fix}
export USHens_tracker=${USHens_tracker:-$HOMEens_tracker/ush}
export SCRIPTens_tracker=${SCRIPTens_tracker:-$HOMEens_tracker/scripts}

##############################
# Run setpdy and initialize PDY variables
##############################
#setpdy.sh
export PDY=20260911
##############################################
# Define COM directories
##############################################
export JYYYY=`echo ${PDY} | cut -c1-4`
export trkrtype='tcgen'
#export COMIN=${COMIN:-$(compath.py -o $NET/${ens_tracker_ver})/${RUN}.${PDY}/${cyc}/pgrba}
#export COMINgfs=${COMINgfs:-$(compath.py $envir/com/gfs/${gfs_ver})/gfs.${PDY}}
#export COMINsyn=${COMINsyn:-$(compath.py $envir/com/gfs/${gfs_ver})/syndat}
#export COMINgenvit=${COMINgenvit:-$(compath.py -o ${NET}/${ens_tracker_ver})/genesis_vital_${JYYYY}}

#export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${ens_tracker_ver})/${RUN}.${PDY}/${cyc}/genesis}
export COMIN=/lfs/h1/ops/prod/com/ens_tracker/v1.3/ecme.20260911/00/pgrba
export COMINgfs=/lfs/h1/ops/prod/com/gfs/v16.3/gfs.${PDY}
export COMINsyn=/lfs/h1/ops/prod/com/gfs/v16.3/syndat
export COMINgenvit=/lfs/h1/ops/prod/com/ens_tracker/v1.3/genesis_vital_2026

export COMOUT=${COMOUT:-${COMROOT:?}/ecmwf.${PDY}/${cyc}/products/atmos/cyclone/genesis}
mkdir -m 775 -p $COMOUT
export='tcgen'

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

#############################################################
# Execute the script

export cmodel=eens
export loopnum=1

export ecedir=${COMIN}
export trkrtype='tcgen'
export regtype=altg

ymdh=${PDY}${cyc}

mkdir ${DATA}/${cmodel}
cd ${DATA}/${cmodel}

pertstring="p01 p02 p03 p04 p05 p06 p07 p08 p09 p10\
            p11 p12 p13 p14 p15 p16 p17 p18 p19 p20\
            p21 p22 p23 p24 p25 \
            n01 n02 n03 n04 n05 n06 n07 n08 n09 n10\
            n11 n12 n13 n14 n15 n16 n17 n18 n19 n20\
            n21 n22 n23 n24 n25"

>trkr.cmdfile
for pert in ${pertstring}; do
  export pertdir=${DATA}/${cmodel}/${pert}
  mkdir -p $pertdir

  outfile=${pertdir}/trkr.${regtype}.${cmodel}.${pert}.${ymdh}.out
  echo "${USHens_tracker}/extrkr_gen_g1.sh ${loopnum} ${cmodel} ${pert} ${pertdir} &>${outfile}" >>trkr.cmdfile
done

chmod u+x trkr.cmdfile
export MP_PGMMODEL=mpmd
export MP_CMDFILE=${DATA}/${cmodel}/trkr.cmdfile

mpiexec --cpu-bind core --configfile ${MP_CMDFILE}
export err=$?; err_chk

exit
for model in ${pertstring}; do
    export model_id="e${model}"
    ${SCRIPTens_tracker}/run_atcf_gen_filter_from_datelist_min24h_3bas.sh ${model_id}
    export err=$?; err_chk
done    


msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
if [[ $KEEPDATA != "YES" ]]; then
  rm -rf $DATA
fi

date
